// Copies Monaco's prebuilt AMD bundle into the extension so it ships fully offline,
// along with the license files (MIT requires them to travel with the code).
const fs = require('fs');
const path = require('path');

const pkg = path.join(__dirname, '..', 'node_modules', 'monaco-editor');
const root = path.join(__dirname, '..', 'extension', 'monaco');

fs.rmSync(root, { recursive: true, force: true });
fs.cpSync(path.join(pkg, 'min', 'vs'), path.join(root, 'vs'), { recursive: true });
for (const file of ['LICENSE', 'ThirdPartyNotices.txt']) {
  fs.copyFileSync(path.join(pkg, file), path.join(root, file));
}
// Emmet for HTML/CSS. The plain-script build defines a single `emmetMonaco` global.
const emmet = path.join(__dirname, '..', 'node_modules', 'emmet-monaco-es');
fs.mkdirSync(path.join(root, 'emmet'));
fs.copyFileSync(path.join(emmet, 'dist', 'emmet-monaco.min.js'), path.join(root, 'emmet', 'emmet-monaco.min.js'));
fs.copyFileSync(path.join(emmet, 'LICENSE'), path.join(root, 'emmet', 'LICENSE'));
// File and folder icons from Material Icon Theme. The editor's CSP blocks fetch(), so the
// name → icon tables are written out as a script that sets `window.CPM_FILE_ICONS`.
const iconTheme = path.join(__dirname, '..', 'node_modules', 'material-icon-theme');
const iconsOut = path.join(root, 'file-icons');
fs.cpSync(path.join(iconTheme, 'icons'), iconsOut, { recursive: true });
fs.copyFileSync(path.join(iconTheme, 'LICENSE'), path.join(iconsOut, 'LICENSE'));
const manifest = JSON.parse(fs.readFileSync(path.join(iconTheme, 'dist', 'material-icons.json'), 'utf8'));
const iconFile = (id) => path.basename(manifest.iconDefinitions[id]?.iconPath || '');
const tables = ['fileNames', 'fileExtensions', 'folderNames', 'folderNamesExpanded', 'languageIds'];
// Lowercase keys (names are matched case-insensitively) and point straight at file names.
const pickTables = (source) => Object.fromEntries(tables.filter((t) => source?.[t]).map((t) => [
  t,
  Object.fromEntries(Object.entries(source[t]).map(([key, id]) => [key.toLowerCase(), iconFile(id)])),
]));
const icons = {
  file: iconFile(manifest.file),
  folder: iconFile(manifest.folder),
  folderExpanded: iconFile(manifest.folderExpanded),
  ...pickTables(manifest),
  light: pickTables(manifest.light),
};
fs.writeFileSync(
  path.join(iconsOut, 'icons.js'),
  `// Generated by scripts/copy-monaco.js from material-icon-theme. Do not edit.\nwindow.CPM_FILE_ICONS = ${JSON.stringify(icons)};\n`,
);

// Prettier with its PHP plugin powers Format Document for PHP. Both are standalone (browser)
// builds, loaded only inside format-worker.js, so they cost nothing until you format a file.
const prettierOut = path.join(root, 'prettier');
fs.mkdirSync(prettierOut);
const prettierPkg = path.join(__dirname, '..', 'node_modules', 'prettier');
const phpPlugin = path.join(__dirname, '..', 'node_modules', '@prettier', 'plugin-php');
fs.copyFileSync(path.join(prettierPkg, 'standalone.js'), path.join(prettierOut, 'standalone.js'));
fs.copyFileSync(path.join(prettierPkg, 'LICENSE'), path.join(prettierOut, 'LICENSE'));
fs.copyFileSync(path.join(phpPlugin, 'standalone.js'), path.join(prettierOut, 'php.js'));
fs.copyFileSync(path.join(phpPlugin, 'LICENSE'), path.join(prettierOut, 'LICENSE-plugin-php'));

// The project's own license ships inside the extension folder too.
fs.copyFileSync(path.join(__dirname, '..', 'LICENSE'), path.join(__dirname, '..', 'extension', 'LICENSE'));
console.log(`Monaco copied to ${path.relative(process.cwd(), root)}`);
